### ISSUE TITLE
deprecate s3 and azure storageTypes

### ISSUE THREAD

**Issue by jhford** [taskcluster/taskcluster-queue#248]
We should deprecate these two storage types.  We should do this as a staged deprecation.

I propose:

1. Announce deprecation
1. One month later, add a new mandatory property to the S3 storage type json schema "i-use-deprectated-storage-types": true, which will break users to alert them that the deprecation is happening.  They can simply fix this by adding a static property to their API calls
1. One month later, disable the ability to create S3 artifacts

This will allow old artifacts to be accessed but no new ones created.

**Comment by djmitche** [comment]
Moved to https://bugzilla.mozilla.org/show_bug.cgi?id=1453513 since this will be a pretty big project.
